python_ver = "cpython-3.14.3"
python_ver_short = "python3.14"
output_dir = "build/final"
python_dir = "python_files"
core_folder = "core"
meson_dir= "build_meson"
download_godot_dir = "godot_zipfile.zip"
dir_godot_extract_to = "godot"