[tool.poetry]
name = "py4godot"
version = "4.7-alpha21"
description = ""
authors = ["Niklas Zimmer <niklas-zimmer@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
wget = "^3.2"
zstandard = "^0.25.0"
cython = "^3.2.9"
meson = "^1.12.0"
ninja = "^1.13.0"
tqdm = "^4.70.0"
beautifulsoup4 = "^4.15.0"
lxml = "^6.1.1"
docker = "^7.2.0"
setuptools = "^84.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
