# distutils: language=c++
cimport py4godot.utils.utils as utils
import py4godot.classes.Object as obj
import py4godot.classes.core as core
cdef dict types_dict = {
int:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_INT,
str:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_STRING,
type(True):GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_BOOL,
float:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_FLOAT,
obj.Object:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_OBJECT,
core.Vector4:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_VECTOR4,
core.PackedColorArray:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY,
core.Vector2i:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_VECTOR2I,
core.Vector3i:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_VECTOR3I,
core.Quaternion:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_QUATERNION,
core.Callable:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_CALLABLE,
core.PackedVector2Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY,
core.Vector4i:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_VECTOR4I,
core.Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_ARRAY,
core.PackedByteArray:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY,
core.AABB:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_AABB,
core.Transform3D:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_TRANSFORM3D,
core.Transform2D:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_TRANSFORM2D,
core.Rect2i:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_RECT2I,
core.PackedFloat64Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY,
core.Dictionary:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_DICTIONARY,
core.PackedStringArray:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY,
core.Plane:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PLANE,
core.PackedInt64Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY,
core.Signal:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_SIGNAL,
core.PackedFloat32Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY,
core.Rect2:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_RECT2,
core.Vector2:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_VECTOR2,
core.NodePath:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_NODE_PATH,
core.Color:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_COLOR,
core.StringName:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_STRING_NAME,
core.RID:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_RID,
core.Projection:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PROJECTION,
core.PackedInt32Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY,
core.Vector3:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_VECTOR3,
core.PackedVector3Array:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY,
core.Basis:GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_BASIS,
}

cdef object convert_val(object val):
    if(type(val) == str):
        return utils.py_c_string_to_string(val.encode("utf-8"))
    return val

cdef GDExtensionVariantType get_variant_type(object type_):
    if(type_ in types_dict.keys()):
        return types_dict[type_]
    print_error("couldn't find type:")
    print_error(str(type_).encode("utf-8"))
    return GDExtensionVariantType.GDEXTENSION_VARIANT_TYPE_NIL
