
from enum import *
from godot_api.binding_external cimport *
cimport classes.VisualInstance
cdef class Light(classes.VisualInstance.VisualInstance):
    pass
ctypedef enum Light_BakeMode :BAKE_DISABLED, BAKE_INDIRECT, BAKE_ALL, 
ctypedef enum Light_Param :PARAM_ENERGY, PARAM_INDIRECT_ENERGY, PARAM_SPECULAR, PARAM_RANGE, PARAM_ATTENUATION, PARAM_SPOT_ANGLE, PARAM_SPOT_ATTENUATION, PARAM_CONTACT_SHADOW_SIZE, PARAM_SHADOW_MAX_DISTANCE, PARAM_SHADOW_SPLIT_1_OFFSET, PARAM_SHADOW_SPLIT_2_OFFSET, PARAM_SHADOW_SPLIT_3_OFFSET, PARAM_SHADOW_NORMAL_BIAS, PARAM_SHADOW_BIAS, PARAM_SHADOW_BIAS_SPLIT_SCALE, PARAM_MAX, 
