
from enum import *
from godot_api.binding_external cimport *
cimport classes.VisualScriptNode
cdef class VisualScriptBuiltinFunc(classes.VisualScriptNode.VisualScriptNode):
    pass
ctypedef enum BuiltinFunc :MATH_SIN, MATH_COS, MATH_TAN, MATH_SINH, MATH_COSH, MATH_TANH, MATH_ASIN, MATH_ACOS, MATH_ATAN, MATH_ATAN2, MATH_SQRT, MATH_FMOD, MATH_FPOSMOD, MATH_FLOOR, MATH_CEIL, MATH_ROUND, MATH_ABS, MATH_SIGN, MATH_POW, MATH_LOG, MATH_EXP, MATH_ISNAN, MATH_ISINF, MATH_EASE, MATH_DECIMALS, MATH_STEPIFY, MATH_LERP, MATH_INVERSE_LERP, MATH_RANGE_LERP, MATH_MOVE_TOWARD, MATH_DECTIME, MATH_RANDOMIZE, MATH_RAND, MATH_RANDF, MATH_RANDOM, MATH_SEED, MATH_RANDSEED, MATH_DEG2RAD, MATH_RAD2DEG, MATH_LINEAR2DB, MATH_DB2LINEAR, MATH_POLAR2CARTESIAN, MATH_CARTESIAN2POLAR, MATH_WRAP, MATH_WRAPF, LOGIC_MAX, LOGIC_MIN, LOGIC_CLAMP, LOGIC_NEAREST_PO2, OBJ_WEAKREF, FUNC_FUNCREF, TYPE_CONVERT, TYPE_OF, TYPE_EXISTS, TEXT_CHAR, TEXT_STR, TEXT_PRINT, TEXT_PRINTERR, TEXT_PRINTRAW, VAR_TO_STR, STR_TO_VAR, VAR_TO_BYTES, BYTES_TO_VAR, COLORN, MATH_SMOOTHSTEP, MATH_POSMOD, MATH_LERP_ANGLE, TEXT_ORD, FUNC_MAX, 
