#include "functions.h"
#include "macros.h"

namespace functions{
// All of the GDExtension interface functions.
GDExtensionInterfaceGetGodotVersion gdextension_interface_get_godot_version = nullptr;
GDExtensionInterfaceMemAlloc gdextension_interface_mem_alloc = nullptr;
GDExtensionInterfaceMemRealloc gdextension_interface_mem_realloc = nullptr;
GDExtensionInterfaceMemFree gdextension_interface_mem_free = nullptr;
GDExtensionInterfacePrintError gdextension_interface_print_error = nullptr;
GDExtensionInterfacePrintErrorWithMessage gdextension_interface_print_error_with_message = nullptr;
GDExtensionInterfacePrintWarning gdextension_interface_print_warning = nullptr;
GDExtensionInterfacePrintWarningWithMessage gdextension_interface_print_warning_with_message = nullptr;
GDExtensionInterfacePrintScriptError gdextension_interface_print_script_error = nullptr;
GDExtensionInterfacePrintScriptErrorWithMessage gdextension_interface_print_script_error_with_message = nullptr;
GDExtensionInterfaceGetNativeStructSize gdextension_interface_get_native_struct_size = nullptr;
GDExtensionInterfaceVariantNewCopy gdextension_interface_variant_new_copy = nullptr;
GDExtensionInterfaceVariantNewNil gdextension_interface_variant_new_nil = nullptr;
GDExtensionInterfaceVariantDestroy gdextension_interface_variant_destroy = nullptr;
GDExtensionInterfaceVariantCall gdextension_interface_variant_call = nullptr;
GDExtensionInterfaceVariantCallStatic gdextension_interface_variant_call_static = nullptr;
GDExtensionInterfaceVariantEvaluate gdextension_interface_variant_evaluate = nullptr;
GDExtensionInterfaceVariantSet gdextension_interface_variant_set = nullptr;
GDExtensionInterfaceVariantSetNamed gdextension_interface_variant_set_named = nullptr;
GDExtensionInterfaceVariantSetKeyed gdextension_interface_variant_set_keyed = nullptr;
GDExtensionInterfaceVariantSetIndexed gdextension_interface_variant_set_indexed = nullptr;
GDExtensionInterfaceVariantGet gdextension_interface_variant_get = nullptr;
GDExtensionInterfaceVariantGetNamed gdextension_interface_variant_get_named = nullptr;
GDExtensionInterfaceVariantGetKeyed gdextension_interface_variant_get_keyed = nullptr;
GDExtensionInterfaceVariantGetIndexed gdextension_interface_variant_get_indexed = nullptr;
GDExtensionInterfaceVariantIterInit gdextension_interface_variant_iter_init = nullptr;
GDExtensionInterfaceVariantIterNext gdextension_interface_variant_iter_next = nullptr;
GDExtensionInterfaceVariantIterGet gdextension_interface_variant_iter_get = nullptr;
GDExtensionInterfaceVariantHash gdextension_interface_variant_hash = nullptr;
GDExtensionInterfaceVariantRecursiveHash gdextension_interface_variant_recursive_hash = nullptr;
GDExtensionInterfaceVariantHashCompare gdextension_interface_variant_hash_compare = nullptr;
GDExtensionInterfaceVariantBooleanize gdextension_interface_variant_booleanize = nullptr;
GDExtensionInterfaceVariantDuplicate gdextension_interface_variant_duplicate = nullptr;
GDExtensionInterfaceVariantStringify gdextension_interface_variant_stringify = nullptr;
GDExtensionInterfaceVariantGetType gdextension_interface_variant_get_type = nullptr;
GDExtensionInterfaceVariantHasMethod gdextension_interface_variant_has_method = nullptr;
GDExtensionInterfaceVariantHasMember gdextension_interface_variant_has_member = nullptr;
GDExtensionInterfaceVariantHasKey gdextension_interface_variant_has_key = nullptr;
GDExtensionInterfaceVariantGetTypeName gdextension_interface_variant_get_type_name = nullptr;
GDExtensionInterfaceVariantCanConvert gdextension_interface_variant_can_convert = nullptr;
GDExtensionInterfaceVariantCanConvertStrict gdextension_interface_variant_can_convert_strict = nullptr;
GDExtensionInterfaceGetVariantFromTypeConstructor gdextension_interface_get_variant_from_type_constructor = nullptr;
GDExtensionInterfaceGetVariantToTypeConstructor gdextension_interface_get_variant_to_type_constructor = nullptr;
GDExtensionInterfaceVariantGetPtrOperatorEvaluator gdextension_interface_variant_get_ptr_operator_evaluator = nullptr;
GDExtensionInterfaceVariantGetPtrBuiltinMethod gdextension_interface_variant_get_ptr_builtin_method = nullptr;
GDExtensionInterfaceVariantGetPtrConstructor gdextension_interface_variant_get_ptr_constructor = nullptr;
GDExtensionInterfaceVariantGetPtrDestructor gdextension_interface_variant_get_ptr_destructor = nullptr;
GDExtensionInterfaceVariantConstruct gdextension_interface_variant_construct = nullptr;
GDExtensionInterfaceVariantGetPtrSetter gdextension_interface_variant_get_ptr_setter = nullptr;
GDExtensionInterfaceVariantGetPtrGetter gdextension_interface_variant_get_ptr_getter = nullptr;
GDExtensionInterfaceVariantGetPtrIndexedSetter gdextension_interface_variant_get_ptr_indexed_setter = nullptr;
GDExtensionInterfaceVariantGetPtrIndexedGetter gdextension_interface_variant_get_ptr_indexed_getter = nullptr;
GDExtensionInterfaceVariantGetPtrKeyedSetter gdextension_interface_variant_get_ptr_keyed_setter = nullptr;
GDExtensionInterfaceVariantGetPtrKeyedGetter gdextension_interface_variant_get_ptr_keyed_getter = nullptr;
GDExtensionInterfaceVariantGetPtrKeyedChecker gdextension_interface_variant_get_ptr_keyed_checker = nullptr;
GDExtensionInterfaceVariantGetConstantValue gdextension_interface_variant_get_constant_value = nullptr;
GDExtensionInterfaceVariantGetPtrUtilityFunction gdextension_interface_variant_get_ptr_utility_function = nullptr;
GDExtensionInterfaceStringNewWithLatin1Chars gdextension_interface_string_new_with_latin1_chars = nullptr;
GDExtensionInterfaceStringNewWithUtf8Chars gdextension_interface_string_new_with_utf8_chars = nullptr;
GDExtensionInterfaceStringNewWithUtf16Chars gdextension_interface_string_new_with_utf16_chars = nullptr;
GDExtensionInterfaceStringNewWithUtf32Chars gdextension_interface_string_new_with_utf32_chars = nullptr;
GDExtensionInterfaceStringNewWithWideChars gdextension_interface_string_new_with_wide_chars = nullptr;
GDExtensionInterfaceStringNewWithLatin1CharsAndLen gdextension_interface_string_new_with_latin1_chars_and_len = nullptr;
GDExtensionInterfaceStringNewWithUtf8CharsAndLen gdextension_interface_string_new_with_utf8_chars_and_len = nullptr;
GDExtensionInterfaceStringNewWithUtf16CharsAndLen gdextension_interface_string_new_with_utf16_chars_and_len = nullptr;
GDExtensionInterfaceStringNewWithUtf32CharsAndLen gdextension_interface_string_new_with_utf32_chars_and_len = nullptr;
GDExtensionInterfaceStringNewWithWideCharsAndLen gdextension_interface_string_new_with_wide_chars_and_len = nullptr;
GDExtensionInterfaceStringToLatin1Chars gdextension_interface_string_to_latin1_chars = nullptr;
GDExtensionInterfaceStringToUtf8Chars gdextension_interface_string_to_utf8_chars = nullptr;
GDExtensionInterfaceStringToUtf16Chars gdextension_interface_string_to_utf16_chars = nullptr;
GDExtensionInterfaceStringToUtf32Chars gdextension_interface_string_to_utf32_chars = nullptr;
GDExtensionInterfaceStringToWideChars gdextension_interface_string_to_wide_chars = nullptr;
GDExtensionInterfaceStringOperatorIndex gdextension_interface_string_operator_index = nullptr;
GDExtensionInterfaceStringOperatorIndexConst gdextension_interface_string_operator_index_const = nullptr;
GDExtensionInterfaceStringOperatorPlusEqString gdextension_interface_string_operator_plus_eq_string = nullptr;
GDExtensionInterfaceStringOperatorPlusEqChar gdextension_interface_string_operator_plus_eq_char = nullptr;
GDExtensionInterfaceStringOperatorPlusEqCstr gdextension_interface_string_operator_plus_eq_cstr = nullptr;
GDExtensionInterfaceStringOperatorPlusEqWcstr gdextension_interface_string_operator_plus_eq_wcstr = nullptr;
GDExtensionInterfaceStringOperatorPlusEqC32str gdextension_interface_string_operator_plus_eq_c32str = nullptr;
GDExtensionInterfaceXmlParserOpenBuffer gdextension_interface_xml_parser_open_buffer = nullptr;
GDExtensionInterfaceFileAccessStoreBuffer gdextension_interface_file_access_store_buffer = nullptr;
GDExtensionInterfaceFileAccessGetBuffer gdextension_interface_file_access_get_buffer = nullptr;
GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask gdextension_interface_worker_thread_pool_add_native_group_task = nullptr;
GDExtensionInterfaceWorkerThreadPoolAddNativeTask gdextension_interface_worker_thread_pool_add_native_task = nullptr;
GDExtensionInterfacePackedByteArrayOperatorIndex gdextension_interface_packed_byte_array_operator_index = nullptr;
GDExtensionInterfacePackedByteArrayOperatorIndexConst gdextension_interface_packed_byte_array_operator_index_const = nullptr;
GDExtensionInterfacePackedColorArrayOperatorIndex gdextension_interface_packed_color_array_operator_index = nullptr;
GDExtensionInterfacePackedColorArrayOperatorIndexConst gdextension_interface_packed_color_array_operator_index_const = nullptr;
GDExtensionInterfacePackedFloat32ArrayOperatorIndex gdextension_interface_packed_float32_array_operator_index = nullptr;
GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst gdextension_interface_packed_float32_array_operator_index_const = nullptr;
GDExtensionInterfacePackedFloat64ArrayOperatorIndex gdextension_interface_packed_float64_array_operator_index = nullptr;
GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst gdextension_interface_packed_float64_array_operator_index_const = nullptr;
GDExtensionInterfacePackedInt32ArrayOperatorIndex gdextension_interface_packed_int32_array_operator_index = nullptr;
GDExtensionInterfacePackedInt32ArrayOperatorIndexConst gdextension_interface_packed_int32_array_operator_index_const = nullptr;
GDExtensionInterfacePackedInt64ArrayOperatorIndex gdextension_interface_packed_int64_array_operator_index = nullptr;
GDExtensionInterfacePackedInt64ArrayOperatorIndexConst gdextension_interface_packed_int64_array_operator_index_const = nullptr;
GDExtensionInterfacePackedStringArrayOperatorIndex gdextension_interface_packed_string_array_operator_index = nullptr;
GDExtensionInterfacePackedStringArrayOperatorIndexConst gdextension_interface_packed_string_array_operator_index_const = nullptr;
GDExtensionInterfacePackedVector2ArrayOperatorIndex gdextension_interface_packed_vector2_array_operator_index = nullptr;
GDExtensionInterfacePackedVector2ArrayOperatorIndexConst gdextension_interface_packed_vector2_array_operator_index_const = nullptr;
GDExtensionInterfacePackedVector3ArrayOperatorIndex gdextension_interface_packed_vector3_array_operator_index = nullptr;
GDExtensionInterfacePackedVector3ArrayOperatorIndexConst gdextension_interface_packed_vector3_array_operator_index_const = nullptr;
GDExtensionInterfaceArrayOperatorIndex gdextension_interface_array_operator_index = nullptr;
GDExtensionInterfaceArrayOperatorIndexConst gdextension_interface_array_operator_index_const = nullptr;
GDExtensionInterfaceArrayRef gdextension_interface_array_ref = nullptr;
GDExtensionInterfaceArraySetTyped gdextension_interface_array_set_typed = nullptr;
GDExtensionInterfaceDictionaryOperatorIndex gdextension_interface_dictionary_operator_index = nullptr;
GDExtensionInterfaceDictionaryOperatorIndexConst gdextension_interface_dictionary_operator_index_const = nullptr;
GDExtensionInterfaceObjectMethodBindCall gdextension_interface_object_method_bind_call = nullptr;
GDExtensionInterfaceObjectMethodBindPtrcall gdextension_interface_object_method_bind_ptrcall = nullptr;
GDExtensionInterfaceObjectDestroy gdextension_interface_object_destroy = nullptr;
GDExtensionInterfaceGlobalGetSingleton gdextension_interface_global_get_singleton = nullptr;
GDExtensionInterfaceObjectGetInstanceBinding gdextension_interface_object_get_instance_binding = nullptr;
GDExtensionInterfaceObjectSetInstanceBinding gdextension_interface_object_set_instance_binding = nullptr;
GDExtensionInterfaceObjectSetInstance gdextension_interface_object_set_instance = nullptr;
GDExtensionInterfaceObjectGetClassName gdextension_interface_object_get_class_name = nullptr;
GDExtensionInterfaceObjectCastTo gdextension_interface_object_cast_to = nullptr;
GDExtensionInterfaceObjectGetInstanceFromId gdextension_interface_object_get_instance_from_id = nullptr;
GDExtensionInterfaceObjectGetInstanceId gdextension_interface_object_get_instance_id = nullptr;
GDExtensionInterfaceRefGetObject gdextension_interface_ref_get_object = nullptr;
GDExtensionInterfaceRefSetObject gdextension_interface_ref_set_object = nullptr;
GDExtensionInterfaceScriptInstanceCreate gdextension_interface_script_instance_create = nullptr;
GDExtensionInterfaceClassdbConstructObject gdextension_interface_classdb_construct_object = nullptr;
GDExtensionInterfaceClassdbGetMethodBind gdextension_interface_classdb_get_method_bind = nullptr;
GDExtensionInterfaceClassdbGetClassTag gdextension_interface_classdb_get_class_tag = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClass gdextension_interface_classdb_register_extension_class = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClassMethod gdextension_interface_classdb_register_extension_class_method = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant gdextension_interface_classdb_register_extension_class_integer_constant = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClassProperty gdextension_interface_classdb_register_extension_class_property = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup gdextension_interface_classdb_register_extension_class_property_group = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup gdextension_interface_classdb_register_extension_class_property_subgroup = nullptr;
GDExtensionInterfaceClassdbRegisterExtensionClassSignal gdextension_interface_classdb_register_extension_class_signal = nullptr;
GDExtensionInterfaceClassdbUnregisterExtensionClass gdextension_interface_classdb_unregister_extension_class = nullptr;
GDExtensionInterfaceGetLibraryPath gdextension_interface_get_library_path = nullptr;
GDExtensionInterfaceEditorAddPlugin gdextension_interface_editor_add_plugin = nullptr;
GDExtensionInterfaceEditorRemovePlugin gdextension_interface_editor_remove_plugin = nullptr;

GDExtensionInterfaceGetGodotVersion get_get_godot_version(){return gdextension_interface_get_godot_version;}
GDExtensionInterfaceMemAlloc get_mem_alloc(){return gdextension_interface_mem_alloc;}
GDExtensionInterfaceMemRealloc get_mem_realloc(){return gdextension_interface_mem_realloc;}
GDExtensionInterfaceMemFree get_mem_free(){return gdextension_interface_mem_free;}
GDExtensionInterfacePrintError get_print_error(){return gdextension_interface_print_error;}
GDExtensionInterfacePrintErrorWithMessage get_print_error_with_message(){return gdextension_interface_print_error_with_message;}
GDExtensionInterfacePrintWarning get_print_warning(){return gdextension_interface_print_warning;}
GDExtensionInterfacePrintWarningWithMessage get_print_warning_with_message(){return gdextension_interface_print_warning_with_message;}
GDExtensionInterfacePrintScriptError get_print_script_error(){return gdextension_interface_print_script_error;}
GDExtensionInterfacePrintScriptErrorWithMessage get_print_script_error_with_message(){return gdextension_interface_print_script_error_with_message;}
GDExtensionInterfaceGetNativeStructSize get_get_native_struct_size(){return gdextension_interface_get_native_struct_size;}
GDExtensionInterfaceVariantNewCopy get_variant_new_copy(){return gdextension_interface_variant_new_copy;}
GDExtensionInterfaceVariantNewNil get_variant_new_nil(){return gdextension_interface_variant_new_nil;}
GDExtensionInterfaceVariantDestroy get_variant_destroy(){return gdextension_interface_variant_destroy;}
GDExtensionInterfaceVariantCall get_variant_call(){return gdextension_interface_variant_call;}
GDExtensionInterfaceVariantCallStatic get_variant_call_static(){return gdextension_interface_variant_call_static;}
GDExtensionInterfaceVariantEvaluate get_variant_evaluate(){return gdextension_interface_variant_evaluate;}
GDExtensionInterfaceVariantSet get_variant_set(){return gdextension_interface_variant_set;}
GDExtensionInterfaceVariantSetNamed get_variant_set_named(){return gdextension_interface_variant_set_named;}
GDExtensionInterfaceVariantSetKeyed get_variant_set_keyed(){return gdextension_interface_variant_set_keyed;}
GDExtensionInterfaceVariantSetIndexed get_variant_set_indexed(){return gdextension_interface_variant_set_indexed;}
GDExtensionInterfaceVariantGet get_variant_get(){return gdextension_interface_variant_get;}
GDExtensionInterfaceVariantGetNamed get_variant_get_named(){return gdextension_interface_variant_get_named;}
GDExtensionInterfaceVariantGetKeyed get_variant_get_keyed(){return gdextension_interface_variant_get_keyed;}
GDExtensionInterfaceVariantGetIndexed get_variant_get_indexed(){return gdextension_interface_variant_get_indexed;}
GDExtensionInterfaceVariantIterInit get_variant_iter_init(){return gdextension_interface_variant_iter_init;}
GDExtensionInterfaceVariantIterNext get_variant_iter_next(){return gdextension_interface_variant_iter_next;}
GDExtensionInterfaceVariantIterGet get_variant_iter_get(){return gdextension_interface_variant_iter_get;}
GDExtensionInterfaceVariantHash get_variant_hash(){return gdextension_interface_variant_hash;}
GDExtensionInterfaceVariantRecursiveHash get_variant_recursive_hash(){return gdextension_interface_variant_recursive_hash;}
GDExtensionInterfaceVariantHashCompare get_variant_hash_compare(){return gdextension_interface_variant_hash_compare;}
GDExtensionInterfaceVariantBooleanize get_variant_booleanize(){return gdextension_interface_variant_booleanize;}
GDExtensionInterfaceVariantDuplicate get_variant_duplicate(){return gdextension_interface_variant_duplicate;}
GDExtensionInterfaceVariantStringify get_variant_stringify(){return gdextension_interface_variant_stringify;}
GDExtensionInterfaceVariantGetType get_variant_get_type(){return gdextension_interface_variant_get_type;}
GDExtensionInterfaceVariantHasMethod get_variant_has_method(){return gdextension_interface_variant_has_method;}
GDExtensionInterfaceVariantHasMember get_variant_has_member(){return gdextension_interface_variant_has_member;}
GDExtensionInterfaceVariantHasKey get_variant_has_key(){return gdextension_interface_variant_has_key;}
GDExtensionInterfaceVariantGetTypeName get_variant_get_type_name(){return gdextension_interface_variant_get_type_name;}
GDExtensionInterfaceVariantCanConvert get_variant_can_convert(){return gdextension_interface_variant_can_convert;}
GDExtensionInterfaceVariantCanConvertStrict get_variant_can_convert_strict(){return gdextension_interface_variant_can_convert_strict;}
GDExtensionInterfaceGetVariantFromTypeConstructor get_get_variant_from_type_constructor(){return gdextension_interface_get_variant_from_type_constructor;}
GDExtensionInterfaceGetVariantToTypeConstructor get_get_variant_to_type_constructor(){return gdextension_interface_get_variant_to_type_constructor;}
GDExtensionInterfaceVariantGetPtrOperatorEvaluator get_variant_get_ptr_operator_evaluator(){return gdextension_interface_variant_get_ptr_operator_evaluator;}
GDExtensionInterfaceVariantGetPtrBuiltinMethod get_variant_get_ptr_builtin_method(){return gdextension_interface_variant_get_ptr_builtin_method;}
GDExtensionInterfaceVariantGetPtrConstructor get_variant_get_ptr_constructor(){return gdextension_interface_variant_get_ptr_constructor;}
GDExtensionInterfaceVariantGetPtrDestructor get_variant_get_ptr_destructor(){return gdextension_interface_variant_get_ptr_destructor;}
GDExtensionInterfaceVariantConstruct get_variant_construct(){return gdextension_interface_variant_construct;}
GDExtensionInterfaceVariantGetPtrSetter get_variant_get_ptr_setter(){return gdextension_interface_variant_get_ptr_setter;}
GDExtensionInterfaceVariantGetPtrGetter get_variant_get_ptr_getter(){return gdextension_interface_variant_get_ptr_getter;}
GDExtensionInterfaceVariantGetPtrIndexedSetter get_variant_get_ptr_indexed_setter(){return gdextension_interface_variant_get_ptr_indexed_setter;}
GDExtensionInterfaceVariantGetPtrIndexedGetter get_variant_get_ptr_indexed_getter(){return gdextension_interface_variant_get_ptr_indexed_getter;}
GDExtensionInterfaceVariantGetPtrKeyedSetter get_variant_get_ptr_keyed_setter(){return gdextension_interface_variant_get_ptr_keyed_setter;}
GDExtensionInterfaceVariantGetPtrKeyedGetter get_variant_get_ptr_keyed_getter(){return gdextension_interface_variant_get_ptr_keyed_getter;}
GDExtensionInterfaceVariantGetPtrKeyedChecker get_variant_get_ptr_keyed_checker(){return gdextension_interface_variant_get_ptr_keyed_checker;}
GDExtensionInterfaceVariantGetConstantValue get_variant_get_constant_value(){return gdextension_interface_variant_get_constant_value;}
GDExtensionInterfaceVariantGetPtrUtilityFunction get_variant_get_ptr_utility_function(){return gdextension_interface_variant_get_ptr_utility_function;}
GDExtensionInterfaceStringNewWithLatin1Chars get_string_new_with_latin1_chars(){return gdextension_interface_string_new_with_latin1_chars;}
GDExtensionInterfaceStringNewWithUtf8Chars get_string_new_with_utf8_chars(){return gdextension_interface_string_new_with_utf8_chars;}
GDExtensionInterfaceStringNewWithUtf16Chars get_string_new_with_utf16_chars(){return gdextension_interface_string_new_with_utf16_chars;}
GDExtensionInterfaceStringNewWithUtf32Chars get_string_new_with_utf32_chars(){return gdextension_interface_string_new_with_utf32_chars;}
GDExtensionInterfaceStringNewWithWideChars get_string_new_with_wide_chars(){return gdextension_interface_string_new_with_wide_chars;}
GDExtensionInterfaceStringNewWithLatin1CharsAndLen get_string_new_with_latin1_chars_and_len(){return gdextension_interface_string_new_with_latin1_chars_and_len;}
GDExtensionInterfaceStringNewWithUtf8CharsAndLen get_string_new_with_utf8_chars_and_len(){return gdextension_interface_string_new_with_utf8_chars_and_len;}
GDExtensionInterfaceStringNewWithUtf16CharsAndLen get_string_new_with_utf16_chars_and_len(){return gdextension_interface_string_new_with_utf16_chars_and_len;}
GDExtensionInterfaceStringNewWithUtf32CharsAndLen get_string_new_with_utf32_chars_and_len(){return gdextension_interface_string_new_with_utf32_chars_and_len;}
GDExtensionInterfaceStringNewWithWideCharsAndLen get_string_new_with_wide_chars_and_len(){return gdextension_interface_string_new_with_wide_chars_and_len;}
GDExtensionInterfaceStringToLatin1Chars get_string_to_latin1_chars(){return gdextension_interface_string_to_latin1_chars;}
GDExtensionInterfaceStringToUtf8Chars get_string_to_utf8_chars(){return gdextension_interface_string_to_utf8_chars;}
GDExtensionInterfaceStringToUtf16Chars get_string_to_utf16_chars(){return gdextension_interface_string_to_utf16_chars;}
GDExtensionInterfaceStringToUtf32Chars get_string_to_utf32_chars(){return gdextension_interface_string_to_utf32_chars;}
GDExtensionInterfaceStringToWideChars get_string_to_wide_chars(){return gdextension_interface_string_to_wide_chars;}
GDExtensionInterfaceStringOperatorIndex get_string_operator_index(){return gdextension_interface_string_operator_index;}
GDExtensionInterfaceStringOperatorIndexConst get_string_operator_index_const(){return gdextension_interface_string_operator_index_const;}
GDExtensionInterfaceStringOperatorPlusEqString get_string_operator_plus_eq_string(){return gdextension_interface_string_operator_plus_eq_string;}
GDExtensionInterfaceStringOperatorPlusEqChar get_string_operator_plus_eq_char(){return gdextension_interface_string_operator_plus_eq_char;}
GDExtensionInterfaceStringOperatorPlusEqCstr get_string_operator_plus_eq_cstr(){return gdextension_interface_string_operator_plus_eq_cstr;}
GDExtensionInterfaceStringOperatorPlusEqWcstr get_string_operator_plus_eq_wcstr(){return gdextension_interface_string_operator_plus_eq_wcstr;}
GDExtensionInterfaceStringOperatorPlusEqC32str get_string_operator_plus_eq_c32str(){return gdextension_interface_string_operator_plus_eq_c32str;}
GDExtensionInterfaceXmlParserOpenBuffer get_xml_parser_open_buffer(){return gdextension_interface_xml_parser_open_buffer;}
GDExtensionInterfaceFileAccessStoreBuffer get_file_access_store_buffer(){return gdextension_interface_file_access_store_buffer;}
GDExtensionInterfaceFileAccessGetBuffer get_file_access_get_buffer(){return gdextension_interface_file_access_get_buffer;}
GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask get_worker_thread_pool_add_native_group_task(){return gdextension_interface_worker_thread_pool_add_native_group_task;}
GDExtensionInterfaceWorkerThreadPoolAddNativeTask get_worker_thread_pool_add_native_task(){return gdextension_interface_worker_thread_pool_add_native_task;}
GDExtensionInterfacePackedByteArrayOperatorIndex get_packed_byte_array_operator_index(){return gdextension_interface_packed_byte_array_operator_index;}
GDExtensionInterfacePackedByteArrayOperatorIndexConst get_packed_byte_array_operator_index_const(){return gdextension_interface_packed_byte_array_operator_index_const;}
GDExtensionInterfacePackedColorArrayOperatorIndex get_packed_color_array_operator_index(){return gdextension_interface_packed_color_array_operator_index;}
GDExtensionInterfacePackedColorArrayOperatorIndexConst get_packed_color_array_operator_index_const(){return gdextension_interface_packed_color_array_operator_index_const;}
GDExtensionInterfacePackedFloat32ArrayOperatorIndex get_packed_float32_array_operator_index(){return gdextension_interface_packed_float32_array_operator_index;}
GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst get_packed_float32_array_operator_index_const(){return gdextension_interface_packed_float32_array_operator_index_const;}
GDExtensionInterfacePackedFloat64ArrayOperatorIndex get_packed_float64_array_operator_index(){return gdextension_interface_packed_float64_array_operator_index;}
GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst get_packed_float64_array_operator_index_const(){return gdextension_interface_packed_float64_array_operator_index_const;}
GDExtensionInterfacePackedInt32ArrayOperatorIndex get_packed_int32_array_operator_index(){return gdextension_interface_packed_int32_array_operator_index;}
GDExtensionInterfacePackedInt32ArrayOperatorIndexConst get_packed_int32_array_operator_index_const(){return gdextension_interface_packed_int32_array_operator_index_const;}
GDExtensionInterfacePackedInt64ArrayOperatorIndex get_packed_int64_array_operator_index(){return gdextension_interface_packed_int64_array_operator_index;}
GDExtensionInterfacePackedInt64ArrayOperatorIndexConst get_packed_int64_array_operator_index_const(){return gdextension_interface_packed_int64_array_operator_index_const;}
GDExtensionInterfacePackedStringArrayOperatorIndex get_packed_string_array_operator_index(){return gdextension_interface_packed_string_array_operator_index;}
GDExtensionInterfacePackedStringArrayOperatorIndexConst get_packed_string_array_operator_index_const(){return gdextension_interface_packed_string_array_operator_index_const;}
GDExtensionInterfacePackedVector2ArrayOperatorIndex get_packed_vector2_array_operator_index(){return gdextension_interface_packed_vector2_array_operator_index;}
GDExtensionInterfacePackedVector2ArrayOperatorIndexConst get_packed_vector2_array_operator_index_const(){return gdextension_interface_packed_vector2_array_operator_index_const;}
GDExtensionInterfacePackedVector3ArrayOperatorIndex get_packed_vector3_array_operator_index(){return gdextension_interface_packed_vector3_array_operator_index;}
GDExtensionInterfacePackedVector3ArrayOperatorIndexConst get_packed_vector3_array_operator_index_const(){return gdextension_interface_packed_vector3_array_operator_index_const;}
GDExtensionInterfaceArrayOperatorIndex get_array_operator_index(){return gdextension_interface_array_operator_index;}
GDExtensionInterfaceArrayOperatorIndexConst get_array_operator_index_const(){return gdextension_interface_array_operator_index_const;}
GDExtensionInterfaceArrayRef get_array_ref(){return gdextension_interface_array_ref;}
GDExtensionInterfaceArraySetTyped get_array_set_typed(){return gdextension_interface_array_set_typed;}
GDExtensionInterfaceDictionaryOperatorIndex get_dictionary_operator_index(){return gdextension_interface_dictionary_operator_index;}
GDExtensionInterfaceDictionaryOperatorIndexConst get_dictionary_operator_index_const(){return gdextension_interface_dictionary_operator_index_const;}
GDExtensionInterfaceObjectMethodBindCall get_object_method_bind_call(){return gdextension_interface_object_method_bind_call;}
GDExtensionInterfaceObjectMethodBindPtrcall& get_object_method_bind_ptrcall(){return gdextension_interface_object_method_bind_ptrcall;}
GDExtensionInterfaceObjectDestroy get_object_destroy(){return gdextension_interface_object_destroy;}
GDExtensionInterfaceGlobalGetSingleton get_global_get_singleton(){return gdextension_interface_global_get_singleton;}
GDExtensionInterfaceObjectGetInstanceBinding get_object_get_instance_binding(){return gdextension_interface_object_get_instance_binding;}
GDExtensionInterfaceObjectSetInstanceBinding get_object_set_instance_binding(){return gdextension_interface_object_set_instance_binding;}
GDExtensionInterfaceObjectSetInstance get_object_set_instance(){return gdextension_interface_object_set_instance;}
GDExtensionInterfaceObjectGetClassName get_object_get_class_name(){return gdextension_interface_object_get_class_name;}
GDExtensionInterfaceObjectCastTo get_object_cast_to(){return gdextension_interface_object_cast_to;}
GDExtensionInterfaceObjectGetInstanceFromId get_object_get_instance_from_id(){return gdextension_interface_object_get_instance_from_id;}
GDExtensionInterfaceObjectGetInstanceId get_object_get_instance_id(){return gdextension_interface_object_get_instance_id;}
GDExtensionInterfaceRefGetObject get_ref_get_object(){return gdextension_interface_ref_get_object;}
GDExtensionInterfaceRefSetObject get_ref_set_object(){return gdextension_interface_ref_set_object;}
GDExtensionInterfaceScriptInstanceCreate get_script_instance_create(){return gdextension_interface_script_instance_create;}
GDExtensionInterfaceClassdbConstructObject get_classdb_construct_object(){return gdextension_interface_classdb_construct_object;}
GDExtensionInterfaceClassdbGetMethodBind get_classdb_get_method_bind(){return gdextension_interface_classdb_get_method_bind;}
GDExtensionInterfaceClassdbGetClassTag get_classdb_get_class_tag(){return gdextension_interface_classdb_get_class_tag;}
GDExtensionInterfaceClassdbRegisterExtensionClass get_classdb_register_extension_class(){return gdextension_interface_classdb_register_extension_class;}
GDExtensionInterfaceClassdbRegisterExtensionClassMethod get_classdb_register_extension_class_method(){return gdextension_interface_classdb_register_extension_class_method;}
GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant get_classdb_register_extension_class_integer_constant(){return gdextension_interface_classdb_register_extension_class_integer_constant;}
GDExtensionInterfaceClassdbRegisterExtensionClassProperty get_classdb_register_extension_class_property(){return gdextension_interface_classdb_register_extension_class_property;}
GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup get_classdb_register_extension_class_property_group(){return gdextension_interface_classdb_register_extension_class_property_group;}
GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup get_classdb_register_extension_class_property_subgroup(){return gdextension_interface_classdb_register_extension_class_property_subgroup;}
GDExtensionInterfaceClassdbRegisterExtensionClassSignal get_classdb_register_extension_class_signal(){return gdextension_interface_classdb_register_extension_class_signal;}
GDExtensionInterfaceClassdbUnregisterExtensionClass get_classdb_unregister_extension_class(){return gdextension_interface_classdb_unregister_extension_class;}
GDExtensionInterfaceGetLibraryPath get_get_library_path(){return gdextension_interface_get_library_path;}
GDExtensionInterfaceEditorAddPlugin get_editor_add_plugin(){return gdextension_interface_editor_add_plugin;}
GDExtensionInterfaceEditorRemovePlugin get_editor_remove_plugin(){return gdextension_interface_editor_remove_plugin;}

} // namespace internal
