/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__godot_api__delorean
#define __PYX_HAVE__godot_api__delorean

#include "Python.h"
struct Vehicle;

/* "godot_api/delorean.pyx":3
 * # delorean.pyx
 * 
 * cdef public struct Vehicle:             # <<<<<<<<<<<<<<
 *     int speed
 *     float power
 */
struct Vehicle {
  int speed;
  float power;
};

#ifndef __PYX_HAVE_API__godot_api__delorean

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__godot_api__delorean */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdelorean(void);
#else
PyMODINIT_FUNC PyInit_delorean(void);
#endif

#endif /* !__PYX_HAVE__godot_api__delorean */
