name: release linux
on:
  workflow_dispatch:

jobs:
  linux-build:
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    container: niklas2902/py4godot:4.4
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          submodules: 'recursive'

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.3"

      - name: Cache py4godot/classes directory
        id: cache-py4godot-classes
        uses: actions/cache@v3
        with:
          path: py4godot/classes
          key: ${{ runner.os }}-py4godot-classes-${{ hashFiles('**/generate_classes.py', '**/generate_pxd_bridge.py', '**/extension_api.json') }}
          restore-keys: |
            ${{ runner.os }}-py4godot-classes-

      - name: Run Python script and check result
        shell: bash
        run: |
          set +e
          python meson_scripts/does_cache_exist.py
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Cache exists"
            # Add any actions you want to take on success
          else
            echo "Cache does not exist"
            exit 0
          fi
          set -e

      - name: Print variables
        run: |
          python meson_scripts/variables.py

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install flake8

      - name: Print structure
        run: python meson_scripts/print_tools.py

      - name: Generate files
        run: python generate.py

      - name: Conditional cythonize
        shell: bash
        run: python cythonize_files.py

      - name: Build
        run: python build.py --target_platform=linux64 --compiler=gcc -create_plugin=False -buildtype=release -run_tests=True -download_godot=True

      - name: Create cache
        run: python meson_scripts/create_cache.py

      - name: Print structure
        run: python meson_scripts/print_tools.py