name: nightly linuxarm
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # run at 3 AM UTC

jobs:
  linuxarm-build:
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    container:
      image: niklas2902/py4godot_arm64:4.4

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 130-support-linuxarm64
          submodules: 'recursive'

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.3"

      - name: Cache py4godot/classes directory
        id: cache-py4godot-classes
        uses: actions/cache@v3
        with:
          path: py4godot/classes
          key: linuxarm64-py4godot-classes-${{ hashFiles('**/generate_classes.py', '**/generate_pxd_bridge.py', '**/extension_api.json') }}
          restore-keys: |
            linuxarm64-py4godot-classes-

      - name: Run Python script and check result
        shell: bash
        run: |
          set +e
          python meson_scripts/does_cache_exist.py
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Cache exists"
          else
            echo "Cache does not exist"
            exit 0
          fi
          set -e

      - name: Print variables
        run: |
          python meson_scripts/variables.py

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: linuxarm64-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            linuxarm64-pip-

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install flake8

      - name: Print structure
        run: python meson_scripts/print_tools.py

      - name: Generate files
        run: python generate.py -dev_build=True

      - name: Conditional cythonize
        shell: bash
        run: |
          set +e
          python meson_scripts/does_cache_exist.py
          exit_code=$?
          set -e
          if [ $exit_code -eq 0 ]; then
            echo "Cache hit for py4godot/classes directory"
            python cythonize_files.py -mode="cache"
          else
            echo "Cache miss for py4godot/classes directory"
            python cythonize_files.py -mode="dev"
          fi

      - name: Build
        run: python build.py --target_platform=linuxarm64 --compiler=gcc -create_plugin=False -buildtype=release -run_tests=True -download_godot=True

      - name: Create cache
        run: python meson_scripts/create_cache.py

      - name: Print structure
        run: python meson_scripts/print_tools.py
