name: WEEKLY windows-arm64
on:
  push:
    branches:
      - winarm64      # or 'master', or use ['main', 'dev', 'feature/*'] for multiple

jobs:
  windows-build:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          submodules: 'recursive'

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.3"
          architecture: arm64

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Generate files
        run: python generate.py -dev_build=True

      - name: Cythonize
        shell: bash
        run: |
            python -m pip install -r requirements.txt
            python cythonize_files.py -mode="dev"

      - name: Build
        shell: cmd
        run: |
          python -m pip install -r requirements.txt
          python build.py --target_platform=windowsarm64 --compiler=gcc -create_plugin=False -buildtype=release -run_tests=False

